apiVersion: apps/v1
kind: Deployment
metadata:
  name: leadsquared-gis-processor
  namespace: leadsquared
  labels:
    app: leadsquared-gis-processor
spec:
  replicas: 0
  selector:
    matchLabels:
      app: leadsquared-gis-processor
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: leadsquared-gis-processor
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001      
        fsGroup: 1001      
      containers:
      - name: leadsquared-gis-processor
        # IMPORTANT: The image tag will be updated by your CI/CD pipeline (e.g., ArgoCD Image Updater)
        image: bom.ocir.io/bm4vulrtwoqg/leadsquared-gis-processor:304fed9
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        envFrom:
        - secretRef:
            name: leadsquared-secret
        
        # Probes are essential for Kubernetes to manage your app's lifecycle
        # livenessProbe:
        #   httpGet:
        #     path: /health # Your new health check endpoint
        #     port: http
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
        # readinessProbe:
        #   httpGet:
        #     path: /health # Your new health check endpoint
        #     port: http
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        
        nodeSelector:
          node-role: light-weight-worker 

        resources:
          requests:
            cpu: "150m"
            memory: "512Mi" 
          limits:
            cpu: "400m" 
            memory: "1Gi"   
        
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        
        # Provide a writable /tmp directory since the root filesystem is read-only
        # FastAPI/Uvicorn may need this for handling file uploads.
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
      volumes:
      - name: tmp-volume
        emptyDir: {}